// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file lidardata.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef FAST_DDS_GENERATED__LIDAR_LIDARDATA_HPP
#define FAST_DDS_GENERATED__LIDAR_LIDARDATA_HPP

#include <array>
#include <cstdint>
#include <utility>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(LIDARDATA_SOURCE)
#define LIDARDATA_DllAPI __declspec( dllexport )
#else
#define LIDARDATA_DllAPI __declspec( dllimport )
#endif // LIDARDATA_SOURCE
#else
#define LIDARDATA_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define LIDARDATA_DllAPI
#endif // _WIN32

namespace Lidar {

/*!
 * @brief This class represents the structure Header defined by the user in the IDL file.
 * @ingroup lidardata
 */
class Header
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Header()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Header()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Header that will be copied.
     */
    eProsima_user_DllExport Header(
            const Header& x)
    {
                    m_seq = x.m_seq;

                    m_timestamp_sec = x.m_timestamp_sec;

                    m_timestamp_usec = x.m_timestamp_usec;

                    m_utc_timestamp_sec = x.m_utc_timestamp_sec;

                    m_topic = x.m_topic;

                    m_cycle_time = x.m_cycle_time;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Header that will be copied.
     */
    eProsima_user_DllExport Header(
            Header&& x) noexcept
    {
        m_seq = x.m_seq;
        m_timestamp_sec = x.m_timestamp_sec;
        m_timestamp_usec = x.m_timestamp_usec;
        m_utc_timestamp_sec = x.m_utc_timestamp_sec;
        m_topic = std::move(x.m_topic);
        m_cycle_time = x.m_cycle_time;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Header that will be copied.
     */
    eProsima_user_DllExport Header& operator =(
            const Header& x)
    {

                    m_seq = x.m_seq;

                    m_timestamp_sec = x.m_timestamp_sec;

                    m_timestamp_usec = x.m_timestamp_usec;

                    m_utc_timestamp_sec = x.m_utc_timestamp_sec;

                    m_topic = x.m_topic;

                    m_cycle_time = x.m_cycle_time;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Header that will be copied.
     */
    eProsima_user_DllExport Header& operator =(
            Header&& x) noexcept
    {

        m_seq = x.m_seq;
        m_timestamp_sec = x.m_timestamp_sec;
        m_timestamp_usec = x.m_timestamp_usec;
        m_utc_timestamp_sec = x.m_utc_timestamp_sec;
        m_topic = std::move(x.m_topic);
        m_cycle_time = x.m_cycle_time;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x Header object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Header& x) const
    {
        return (m_seq == x.m_seq &&
           m_timestamp_sec == x.m_timestamp_sec &&
           m_timestamp_usec == x.m_timestamp_usec &&
           m_utc_timestamp_sec == x.m_utc_timestamp_sec &&
           m_topic == x.m_topic &&
           m_cycle_time == x.m_cycle_time);
    }

    /*!
     * @brief Comparison operator.
     * @param x Header object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Header& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member seq
     * @param _seq New value for member seq
     */
    eProsima_user_DllExport void seq(
            uint32_t _seq)
    {
        m_seq = _seq;
    }

    /*!
     * @brief This function returns the value of member seq
     * @return Value of member seq
     */
    eProsima_user_DllExport uint32_t seq() const
    {
        return m_seq;
    }

    /*!
     * @brief This function returns a reference to member seq
     * @return Reference to member seq
     */
    eProsima_user_DllExport uint32_t& seq()
    {
        return m_seq;
    }


    /*!
     * @brief This function sets a value in member timestamp_sec
     * @param _timestamp_sec New value for member timestamp_sec
     */
    eProsima_user_DllExport void timestamp_sec(
            uint32_t _timestamp_sec)
    {
        m_timestamp_sec = _timestamp_sec;
    }

    /*!
     * @brief This function returns the value of member timestamp_sec
     * @return Value of member timestamp_sec
     */
    eProsima_user_DllExport uint32_t timestamp_sec() const
    {
        return m_timestamp_sec;
    }

    /*!
     * @brief This function returns a reference to member timestamp_sec
     * @return Reference to member timestamp_sec
     */
    eProsima_user_DllExport uint32_t& timestamp_sec()
    {
        return m_timestamp_sec;
    }


    /*!
     * @brief This function sets a value in member timestamp_usec
     * @param _timestamp_usec New value for member timestamp_usec
     */
    eProsima_user_DllExport void timestamp_usec(
            uint32_t _timestamp_usec)
    {
        m_timestamp_usec = _timestamp_usec;
    }

    /*!
     * @brief This function returns the value of member timestamp_usec
     * @return Value of member timestamp_usec
     */
    eProsima_user_DllExport uint32_t timestamp_usec() const
    {
        return m_timestamp_usec;
    }

    /*!
     * @brief This function returns a reference to member timestamp_usec
     * @return Reference to member timestamp_usec
     */
    eProsima_user_DllExport uint32_t& timestamp_usec()
    {
        return m_timestamp_usec;
    }


    /*!
     * @brief This function sets a value in member utc_timestamp_sec
     * @param _utc_timestamp_sec New value for member utc_timestamp_sec
     */
    eProsima_user_DllExport void utc_timestamp_sec(
            uint64_t _utc_timestamp_sec)
    {
        m_utc_timestamp_sec = _utc_timestamp_sec;
    }

    /*!
     * @brief This function returns the value of member utc_timestamp_sec
     * @return Value of member utc_timestamp_sec
     */
    eProsima_user_DllExport uint64_t utc_timestamp_sec() const
    {
        return m_utc_timestamp_sec;
    }

    /*!
     * @brief This function returns a reference to member utc_timestamp_sec
     * @return Reference to member utc_timestamp_sec
     */
    eProsima_user_DllExport uint64_t& utc_timestamp_sec()
    {
        return m_utc_timestamp_sec;
    }


    /*!
     * @brief This function copies the value in member topic
     * @param _topic New value to be copied in member topic
     */
    eProsima_user_DllExport void topic(
            const std::array<uint8_t, 64>& _topic)
    {
        m_topic = _topic;
    }

    /*!
     * @brief This function moves the value in member topic
     * @param _topic New value to be moved in member topic
     */
    eProsima_user_DllExport void topic(
            std::array<uint8_t, 64>&& _topic)
    {
        m_topic = std::move(_topic);
    }

    /*!
     * @brief This function returns a constant reference to member topic
     * @return Constant reference to member topic
     */
    eProsima_user_DllExport const std::array<uint8_t, 64>& topic() const
    {
        return m_topic;
    }

    /*!
     * @brief This function returns a reference to member topic
     * @return Reference to member topic
     */
    eProsima_user_DllExport std::array<uint8_t, 64>& topic()
    {
        return m_topic;
    }


    /*!
     * @brief This function sets a value in member cycle_time
     * @param _cycle_time New value for member cycle_time
     */
    eProsima_user_DllExport void cycle_time(
            uint32_t _cycle_time)
    {
        m_cycle_time = _cycle_time;
    }

    /*!
     * @brief This function returns the value of member cycle_time
     * @return Value of member cycle_time
     */
    eProsima_user_DllExport uint32_t cycle_time() const
    {
        return m_cycle_time;
    }

    /*!
     * @brief This function returns a reference to member cycle_time
     * @return Reference to member cycle_time
     */
    eProsima_user_DllExport uint32_t& cycle_time()
    {
        return m_cycle_time;
    }



private:

    uint32_t m_seq{0};
    uint32_t m_timestamp_sec{0};
    uint32_t m_timestamp_usec{0};
    uint64_t m_utc_timestamp_sec{0};
    std::array<uint8_t, 64> m_topic{0};
    uint32_t m_cycle_time{0};

};
/*!
 * @brief This class represents the structure Suffix defined by the user in the IDL file.
 * @ingroup lidardata
 */
class Suffix
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Suffix()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Suffix()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Suffix that will be copied.
     */
    eProsima_user_DllExport Suffix(
            const Suffix& x)
    {
                    m_suff = x.m_suff;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Suffix that will be copied.
     */
    eProsima_user_DllExport Suffix(
            Suffix&& x) noexcept
    {
        m_suff = std::move(x.m_suff);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Suffix that will be copied.
     */
    eProsima_user_DllExport Suffix& operator =(
            const Suffix& x)
    {

                    m_suff = x.m_suff;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Suffix that will be copied.
     */
    eProsima_user_DllExport Suffix& operator =(
            Suffix&& x) noexcept
    {

        m_suff = std::move(x.m_suff);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x Suffix object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Suffix& x) const
    {
        return (m_suff == x.m_suff);
    }

    /*!
     * @brief Comparison operator.
     * @param x Suffix object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Suffix& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member suff
     * @param _suff New value to be copied in member suff
     */
    eProsima_user_DllExport void suff(
            const std::array<uint8_t, 64>& _suff)
    {
        m_suff = _suff;
    }

    /*!
     * @brief This function moves the value in member suff
     * @param _suff New value to be moved in member suff
     */
    eProsima_user_DllExport void suff(
            std::array<uint8_t, 64>&& _suff)
    {
        m_suff = std::move(_suff);
    }

    /*!
     * @brief This function returns a constant reference to member suff
     * @return Constant reference to member suff
     */
    eProsima_user_DllExport const std::array<uint8_t, 64>& suff() const
    {
        return m_suff;
    }

    /*!
     * @brief This function returns a reference to member suff
     * @return Reference to member suff
     */
    eProsima_user_DllExport std::array<uint8_t, 64>& suff()
    {
        return m_suff;
    }



private:

    std::array<uint8_t, 64> m_suff{0};

};
/*!
 * @brief This class represents the structure ChannelData defined by the user in the IDL file.
 * @ingroup lidardata
 */
class ChannelData
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport ChannelData()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~ChannelData()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object ChannelData that will be copied.
     */
    eProsima_user_DllExport ChannelData(
            const ChannelData& x)
    {
                    m_x = x.m_x;

                    m_y = x.m_y;

                    m_z = x.m_z;

                    m_intensity = x.m_intensity;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object ChannelData that will be copied.
     */
    eProsima_user_DllExport ChannelData(
            ChannelData&& x) noexcept
    {
        m_x = x.m_x;
        m_y = x.m_y;
        m_z = x.m_z;
        m_intensity = x.m_intensity;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object ChannelData that will be copied.
     */
    eProsima_user_DllExport ChannelData& operator =(
            const ChannelData& x)
    {

                    m_x = x.m_x;

                    m_y = x.m_y;

                    m_z = x.m_z;

                    m_intensity = x.m_intensity;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object ChannelData that will be copied.
     */
    eProsima_user_DllExport ChannelData& operator =(
            ChannelData&& x) noexcept
    {

        m_x = x.m_x;
        m_y = x.m_y;
        m_z = x.m_z;
        m_intensity = x.m_intensity;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x ChannelData object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const ChannelData& x) const
    {
        return (m_x == x.m_x &&
           m_y == x.m_y &&
           m_z == x.m_z &&
           m_intensity == x.m_intensity);
    }

    /*!
     * @brief Comparison operator.
     * @param x ChannelData object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const ChannelData& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member x
     * @param _x New value for member x
     */
    eProsima_user_DllExport void x(
            float _x)
    {
        m_x = _x;
    }

    /*!
     * @brief This function returns the value of member x
     * @return Value of member x
     */
    eProsima_user_DllExport float x() const
    {
        return m_x;
    }

    /*!
     * @brief This function returns a reference to member x
     * @return Reference to member x
     */
    eProsima_user_DllExport float& x()
    {
        return m_x;
    }


    /*!
     * @brief This function sets a value in member y
     * @param _y New value for member y
     */
    eProsima_user_DllExport void y(
            float _y)
    {
        m_y = _y;
    }

    /*!
     * @brief This function returns the value of member y
     * @return Value of member y
     */
    eProsima_user_DllExport float y() const
    {
        return m_y;
    }

    /*!
     * @brief This function returns a reference to member y
     * @return Reference to member y
     */
    eProsima_user_DllExport float& y()
    {
        return m_y;
    }


    /*!
     * @brief This function sets a value in member z
     * @param _z New value for member z
     */
    eProsima_user_DllExport void z(
            float _z)
    {
        m_z = _z;
    }

    /*!
     * @brief This function returns the value of member z
     * @return Value of member z
     */
    eProsima_user_DllExport float z() const
    {
        return m_z;
    }

    /*!
     * @brief This function returns a reference to member z
     * @return Reference to member z
     */
    eProsima_user_DllExport float& z()
    {
        return m_z;
    }


    /*!
     * @brief This function sets a value in member intensity
     * @param _intensity New value for member intensity
     */
    eProsima_user_DllExport void intensity(
            uint8_t _intensity)
    {
        m_intensity = _intensity;
    }

    /*!
     * @brief This function returns the value of member intensity
     * @return Value of member intensity
     */
    eProsima_user_DllExport uint8_t intensity() const
    {
        return m_intensity;
    }

    /*!
     * @brief This function returns a reference to member intensity
     * @return Reference to member intensity
     */
    eProsima_user_DllExport uint8_t& intensity()
    {
        return m_intensity;
    }



private:

    float m_x{0.0};
    float m_y{0.0};
    float m_z{0.0};
    uint8_t m_intensity{0};

};
/*!
 * @brief This class represents the structure DataBlock defined by the user in the IDL file.
 * @ingroup lidardata
 */
class DataBlock
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport DataBlock()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~DataBlock()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object DataBlock that will be copied.
     */
    eProsima_user_DllExport DataBlock(
            const DataBlock& x)
    {
                    m_time_offset = x.m_time_offset;

                    m_return_seq = x.m_return_seq;

                    m_channel_data_sum = x.m_channel_data_sum;

                    m_channel_data_list = x.m_channel_data_list;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object DataBlock that will be copied.
     */
    eProsima_user_DllExport DataBlock(
            DataBlock&& x) noexcept
    {
        m_time_offset = x.m_time_offset;
        m_return_seq = x.m_return_seq;
        m_channel_data_sum = x.m_channel_data_sum;
        m_channel_data_list = std::move(x.m_channel_data_list);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object DataBlock that will be copied.
     */
    eProsima_user_DllExport DataBlock& operator =(
            const DataBlock& x)
    {

                    m_time_offset = x.m_time_offset;

                    m_return_seq = x.m_return_seq;

                    m_channel_data_sum = x.m_channel_data_sum;

                    m_channel_data_list = x.m_channel_data_list;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object DataBlock that will be copied.
     */
    eProsima_user_DllExport DataBlock& operator =(
            DataBlock&& x) noexcept
    {

        m_time_offset = x.m_time_offset;
        m_return_seq = x.m_return_seq;
        m_channel_data_sum = x.m_channel_data_sum;
        m_channel_data_list = std::move(x.m_channel_data_list);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x DataBlock object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const DataBlock& x) const
    {
        return (m_time_offset == x.m_time_offset &&
           m_return_seq == x.m_return_seq &&
           m_channel_data_sum == x.m_channel_data_sum &&
           m_channel_data_list == x.m_channel_data_list);
    }

    /*!
     * @brief Comparison operator.
     * @param x DataBlock object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const DataBlock& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member time_offset
     * @param _time_offset New value for member time_offset
     */
    eProsima_user_DllExport void time_offset(
            uint8_t _time_offset)
    {
        m_time_offset = _time_offset;
    }

    /*!
     * @brief This function returns the value of member time_offset
     * @return Value of member time_offset
     */
    eProsima_user_DllExport uint8_t time_offset() const
    {
        return m_time_offset;
    }

    /*!
     * @brief This function returns a reference to member time_offset
     * @return Reference to member time_offset
     */
    eProsima_user_DllExport uint8_t& time_offset()
    {
        return m_time_offset;
    }


    /*!
     * @brief This function sets a value in member return_seq
     * @param _return_seq New value for member return_seq
     */
    eProsima_user_DllExport void return_seq(
            uint8_t _return_seq)
    {
        m_return_seq = _return_seq;
    }

    /*!
     * @brief This function returns the value of member return_seq
     * @return Value of member return_seq
     */
    eProsima_user_DllExport uint8_t return_seq() const
    {
        return m_return_seq;
    }

    /*!
     * @brief This function returns a reference to member return_seq
     * @return Reference to member return_seq
     */
    eProsima_user_DllExport uint8_t& return_seq()
    {
        return m_return_seq;
    }


    /*!
     * @brief This function sets a value in member channel_data_sum
     * @param _channel_data_sum New value for member channel_data_sum
     */
    eProsima_user_DllExport void channel_data_sum(
            uint16_t _channel_data_sum)
    {
        m_channel_data_sum = _channel_data_sum;
    }

    /*!
     * @brief This function returns the value of member channel_data_sum
     * @return Value of member channel_data_sum
     */
    eProsima_user_DllExport uint16_t channel_data_sum() const
    {
        return m_channel_data_sum;
    }

    /*!
     * @brief This function returns a reference to member channel_data_sum
     * @return Reference to member channel_data_sum
     */
    eProsima_user_DllExport uint16_t& channel_data_sum()
    {
        return m_channel_data_sum;
    }


    /*!
     * @brief This function copies the value in member channel_data_list
     * @param _channel_data_list New value to be copied in member channel_data_list
     */
    eProsima_user_DllExport void channel_data_list(
            const std::array<ChannelData, 5>& _channel_data_list)
    {
        m_channel_data_list = _channel_data_list;
    }

    /*!
     * @brief This function moves the value in member channel_data_list
     * @param _channel_data_list New value to be moved in member channel_data_list
     */
    eProsima_user_DllExport void channel_data_list(
            std::array<ChannelData, 5>&& _channel_data_list)
    {
        m_channel_data_list = std::move(_channel_data_list);
    }

    /*!
     * @brief This function returns a constant reference to member channel_data_list
     * @return Constant reference to member channel_data_list
     */
    eProsima_user_DllExport const std::array<ChannelData, 5>& channel_data_list() const
    {
        return m_channel_data_list;
    }

    /*!
     * @brief This function returns a reference to member channel_data_list
     * @return Reference to member channel_data_list
     */
    eProsima_user_DllExport std::array<ChannelData, 5>& channel_data_list()
    {
        return m_channel_data_list;
    }



private:

    uint8_t m_time_offset{0};
    uint8_t m_return_seq{0};
    uint16_t m_channel_data_sum{0};
    std::array<ChannelData, 5> m_channel_data_list;

};
/*!
 * @brief This class represents the structure Packet defined by the user in the IDL file.
 * @ingroup lidardata
 */
class Packet
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Packet()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Packet()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Packet that will be copied.
     */
    eProsima_user_DllExport Packet(
            const Packet& x)
    {
                    m_timestamp_secs = x.m_timestamp_secs;

                    m_timestamp_usecs = x.m_timestamp_usecs;

                    m_laser_num = x.m_laser_num;

                    m_data_block_sum = x.m_data_block_sum;

                    m_data_block_list = x.m_data_block_list;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Packet that will be copied.
     */
    eProsima_user_DllExport Packet(
            Packet&& x) noexcept
    {
        m_timestamp_secs = x.m_timestamp_secs;
        m_timestamp_usecs = x.m_timestamp_usecs;
        m_laser_num = x.m_laser_num;
        m_data_block_sum = x.m_data_block_sum;
        m_data_block_list = std::move(x.m_data_block_list);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Packet that will be copied.
     */
    eProsima_user_DllExport Packet& operator =(
            const Packet& x)
    {

                    m_timestamp_secs = x.m_timestamp_secs;

                    m_timestamp_usecs = x.m_timestamp_usecs;

                    m_laser_num = x.m_laser_num;

                    m_data_block_sum = x.m_data_block_sum;

                    m_data_block_list = x.m_data_block_list;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Packet that will be copied.
     */
    eProsima_user_DllExport Packet& operator =(
            Packet&& x) noexcept
    {

        m_timestamp_secs = x.m_timestamp_secs;
        m_timestamp_usecs = x.m_timestamp_usecs;
        m_laser_num = x.m_laser_num;
        m_data_block_sum = x.m_data_block_sum;
        m_data_block_list = std::move(x.m_data_block_list);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x Packet object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Packet& x) const
    {
        return (m_timestamp_secs == x.m_timestamp_secs &&
           m_timestamp_usecs == x.m_timestamp_usecs &&
           m_laser_num == x.m_laser_num &&
           m_data_block_sum == x.m_data_block_sum &&
           m_data_block_list == x.m_data_block_list);
    }

    /*!
     * @brief Comparison operator.
     * @param x Packet object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Packet& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member timestamp_secs
     * @param _timestamp_secs New value for member timestamp_secs
     */
    eProsima_user_DllExport void timestamp_secs(
            uint32_t _timestamp_secs)
    {
        m_timestamp_secs = _timestamp_secs;
    }

    /*!
     * @brief This function returns the value of member timestamp_secs
     * @return Value of member timestamp_secs
     */
    eProsima_user_DllExport uint32_t timestamp_secs() const
    {
        return m_timestamp_secs;
    }

    /*!
     * @brief This function returns a reference to member timestamp_secs
     * @return Reference to member timestamp_secs
     */
    eProsima_user_DllExport uint32_t& timestamp_secs()
    {
        return m_timestamp_secs;
    }


    /*!
     * @brief This function sets a value in member timestamp_usecs
     * @param _timestamp_usecs New value for member timestamp_usecs
     */
    eProsima_user_DllExport void timestamp_usecs(
            uint32_t _timestamp_usecs)
    {
        m_timestamp_usecs = _timestamp_usecs;
    }

    /*!
     * @brief This function returns the value of member timestamp_usecs
     * @return Value of member timestamp_usecs
     */
    eProsima_user_DllExport uint32_t timestamp_usecs() const
    {
        return m_timestamp_usecs;
    }

    /*!
     * @brief This function returns a reference to member timestamp_usecs
     * @return Reference to member timestamp_usecs
     */
    eProsima_user_DllExport uint32_t& timestamp_usecs()
    {
        return m_timestamp_usecs;
    }


    /*!
     * @brief This function sets a value in member laser_num
     * @param _laser_num New value for member laser_num
     */
    eProsima_user_DllExport void laser_num(
            uint8_t _laser_num)
    {
        m_laser_num = _laser_num;
    }

    /*!
     * @brief This function returns the value of member laser_num
     * @return Value of member laser_num
     */
    eProsima_user_DllExport uint8_t laser_num() const
    {
        return m_laser_num;
    }

    /*!
     * @brief This function returns a reference to member laser_num
     * @return Reference to member laser_num
     */
    eProsima_user_DllExport uint8_t& laser_num()
    {
        return m_laser_num;
    }


    /*!
     * @brief This function sets a value in member data_block_sum
     * @param _data_block_sum New value for member data_block_sum
     */
    eProsima_user_DllExport void data_block_sum(
            uint16_t _data_block_sum)
    {
        m_data_block_sum = _data_block_sum;
    }

    /*!
     * @brief This function returns the value of member data_block_sum
     * @return Value of member data_block_sum
     */
    eProsima_user_DllExport uint16_t data_block_sum() const
    {
        return m_data_block_sum;
    }

    /*!
     * @brief This function returns a reference to member data_block_sum
     * @return Reference to member data_block_sum
     */
    eProsima_user_DllExport uint16_t& data_block_sum()
    {
        return m_data_block_sum;
    }


    /*!
     * @brief This function copies the value in member data_block_list
     * @param _data_block_list New value to be copied in member data_block_list
     */
    eProsima_user_DllExport void data_block_list(
            const std::array<DataBlock, 25>& _data_block_list)
    {
        m_data_block_list = _data_block_list;
    }

    /*!
     * @brief This function moves the value in member data_block_list
     * @param _data_block_list New value to be moved in member data_block_list
     */
    eProsima_user_DllExport void data_block_list(
            std::array<DataBlock, 25>&& _data_block_list)
    {
        m_data_block_list = std::move(_data_block_list);
    }

    /*!
     * @brief This function returns a constant reference to member data_block_list
     * @return Constant reference to member data_block_list
     */
    eProsima_user_DllExport const std::array<DataBlock, 25>& data_block_list() const
    {
        return m_data_block_list;
    }

    /*!
     * @brief This function returns a reference to member data_block_list
     * @return Reference to member data_block_list
     */
    eProsima_user_DllExport std::array<DataBlock, 25>& data_block_list()
    {
        return m_data_block_list;
    }



private:

    uint32_t m_timestamp_secs{0};
    uint32_t m_timestamp_usecs{0};
    uint8_t m_laser_num{0};
    uint16_t m_data_block_sum{0};
    std::array<DataBlock, 25> m_data_block_list;

};
/*!
 * @brief This class represents the structure LidarDataDet defined by the user in the IDL file.
 * @ingroup lidardata
 */
class LidarDataDet
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport LidarDataDet()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~LidarDataDet()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object LidarDataDet that will be copied.
     */
    eProsima_user_DllExport LidarDataDet(
            const LidarDataDet& x)
    {
                    m_protocol_version = x.m_protocol_version;

                    m_return_mode = x.m_return_mode;

                    m_time_sync_mode = x.m_time_sync_mode;

                    m_frame_sync = x.m_frame_sync;

                    m_packet_sum = x.m_packet_sum;

                    m_packet_list = x.m_packet_list;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object LidarDataDet that will be copied.
     */
    eProsima_user_DllExport LidarDataDet(
            LidarDataDet&& x) noexcept
    {
        m_protocol_version = x.m_protocol_version;
        m_return_mode = x.m_return_mode;
        m_time_sync_mode = x.m_time_sync_mode;
        m_frame_sync = x.m_frame_sync;
        m_packet_sum = x.m_packet_sum;
        m_packet_list = std::move(x.m_packet_list);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object LidarDataDet that will be copied.
     */
    eProsima_user_DllExport LidarDataDet& operator =(
            const LidarDataDet& x)
    {

                    m_protocol_version = x.m_protocol_version;

                    m_return_mode = x.m_return_mode;

                    m_time_sync_mode = x.m_time_sync_mode;

                    m_frame_sync = x.m_frame_sync;

                    m_packet_sum = x.m_packet_sum;

                    m_packet_list = x.m_packet_list;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object LidarDataDet that will be copied.
     */
    eProsima_user_DllExport LidarDataDet& operator =(
            LidarDataDet&& x) noexcept
    {

        m_protocol_version = x.m_protocol_version;
        m_return_mode = x.m_return_mode;
        m_time_sync_mode = x.m_time_sync_mode;
        m_frame_sync = x.m_frame_sync;
        m_packet_sum = x.m_packet_sum;
        m_packet_list = std::move(x.m_packet_list);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x LidarDataDet object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const LidarDataDet& x) const
    {
        return (m_protocol_version == x.m_protocol_version &&
           m_return_mode == x.m_return_mode &&
           m_time_sync_mode == x.m_time_sync_mode &&
           m_frame_sync == x.m_frame_sync &&
           m_packet_sum == x.m_packet_sum &&
           m_packet_list == x.m_packet_list);
    }

    /*!
     * @brief Comparison operator.
     * @param x LidarDataDet object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const LidarDataDet& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member protocol_version
     * @param _protocol_version New value for member protocol_version
     */
    eProsima_user_DllExport void protocol_version(
            uint16_t _protocol_version)
    {
        m_protocol_version = _protocol_version;
    }

    /*!
     * @brief This function returns the value of member protocol_version
     * @return Value of member protocol_version
     */
    eProsima_user_DllExport uint16_t protocol_version() const
    {
        return m_protocol_version;
    }

    /*!
     * @brief This function returns a reference to member protocol_version
     * @return Reference to member protocol_version
     */
    eProsima_user_DllExport uint16_t& protocol_version()
    {
        return m_protocol_version;
    }


    /*!
     * @brief This function sets a value in member return_mode
     * @param _return_mode New value for member return_mode
     */
    eProsima_user_DllExport void return_mode(
            uint8_t _return_mode)
    {
        m_return_mode = _return_mode;
    }

    /*!
     * @brief This function returns the value of member return_mode
     * @return Value of member return_mode
     */
    eProsima_user_DllExport uint8_t return_mode() const
    {
        return m_return_mode;
    }

    /*!
     * @brief This function returns a reference to member return_mode
     * @return Reference to member return_mode
     */
    eProsima_user_DllExport uint8_t& return_mode()
    {
        return m_return_mode;
    }


    /*!
     * @brief This function sets a value in member time_sync_mode
     * @param _time_sync_mode New value for member time_sync_mode
     */
    eProsima_user_DllExport void time_sync_mode(
            uint8_t _time_sync_mode)
    {
        m_time_sync_mode = _time_sync_mode;
    }

    /*!
     * @brief This function returns the value of member time_sync_mode
     * @return Value of member time_sync_mode
     */
    eProsima_user_DllExport uint8_t time_sync_mode() const
    {
        return m_time_sync_mode;
    }

    /*!
     * @brief This function returns a reference to member time_sync_mode
     * @return Reference to member time_sync_mode
     */
    eProsima_user_DllExport uint8_t& time_sync_mode()
    {
        return m_time_sync_mode;
    }


    /*!
     * @brief This function sets a value in member frame_sync
     * @param _frame_sync New value for member frame_sync
     */
    eProsima_user_DllExport void frame_sync(
            uint8_t _frame_sync)
    {
        m_frame_sync = _frame_sync;
    }

    /*!
     * @brief This function returns the value of member frame_sync
     * @return Value of member frame_sync
     */
    eProsima_user_DllExport uint8_t frame_sync() const
    {
        return m_frame_sync;
    }

    /*!
     * @brief This function returns a reference to member frame_sync
     * @return Reference to member frame_sync
     */
    eProsima_user_DllExport uint8_t& frame_sync()
    {
        return m_frame_sync;
    }


    /*!
     * @brief This function sets a value in member packet_sum
     * @param _packet_sum New value for member packet_sum
     */
    eProsima_user_DllExport void packet_sum(
            uint16_t _packet_sum)
    {
        m_packet_sum = _packet_sum;
    }

    /*!
     * @brief This function returns the value of member packet_sum
     * @return Value of member packet_sum
     */
    eProsima_user_DllExport uint16_t packet_sum() const
    {
        return m_packet_sum;
    }

    /*!
     * @brief This function returns a reference to member packet_sum
     * @return Reference to member packet_sum
     */
    eProsima_user_DllExport uint16_t& packet_sum()
    {
        return m_packet_sum;
    }


    /*!
     * @brief This function copies the value in member packet_list
     * @param _packet_list New value to be copied in member packet_list
     */
    eProsima_user_DllExport void packet_list(
            const std::array<Packet, 630>& _packet_list)
    {
        m_packet_list = _packet_list;
    }

    /*!
     * @brief This function moves the value in member packet_list
     * @param _packet_list New value to be moved in member packet_list
     */
    eProsima_user_DllExport void packet_list(
            std::array<Packet, 630>&& _packet_list)
    {
        m_packet_list = std::move(_packet_list);
    }

    /*!
     * @brief This function returns a constant reference to member packet_list
     * @return Constant reference to member packet_list
     */
    eProsima_user_DllExport const std::array<Packet, 630>& packet_list() const
    {
        return m_packet_list;
    }

    /*!
     * @brief This function returns a reference to member packet_list
     * @return Reference to member packet_list
     */
    eProsima_user_DllExport std::array<Packet, 630>& packet_list()
    {
        return m_packet_list;
    }



private:

    uint16_t m_protocol_version{0};
    uint8_t m_return_mode{0};
    uint8_t m_time_sync_mode{0};
    uint8_t m_frame_sync{0};
    uint16_t m_packet_sum{0};
    std::array<Packet, 630> m_packet_list;

};
/*!
 * @brief This class represents the structure LidarDataDetection defined by the user in the IDL file.
 * @ingroup lidardata
 */
class LidarDataDetection
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport LidarDataDetection()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~LidarDataDetection()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object LidarDataDetection that will be copied.
     */
    eProsima_user_DllExport LidarDataDetection(
            const LidarDataDetection& x)
    {
                    m_header_ = x.m_header_;

                    m_lidardatadet_ = x.m_lidardatadet_;

                    m_suffix_ = x.m_suffix_;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object LidarDataDetection that will be copied.
     */
    eProsima_user_DllExport LidarDataDetection(
            LidarDataDetection&& x) noexcept
    {
        m_header_ = std::move(x.m_header_);
        m_lidardatadet_ = std::move(x.m_lidardatadet_);
        m_suffix_ = std::move(x.m_suffix_);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object LidarDataDetection that will be copied.
     */
    eProsima_user_DllExport LidarDataDetection& operator =(
            const LidarDataDetection& x)
    {

                    m_header_ = x.m_header_;

                    m_lidardatadet_ = x.m_lidardatadet_;

                    m_suffix_ = x.m_suffix_;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object LidarDataDetection that will be copied.
     */
    eProsima_user_DllExport LidarDataDetection& operator =(
            LidarDataDetection&& x) noexcept
    {

        m_header_ = std::move(x.m_header_);
        m_lidardatadet_ = std::move(x.m_lidardatadet_);
        m_suffix_ = std::move(x.m_suffix_);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x LidarDataDetection object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const LidarDataDetection& x) const
    {
        return (m_header_ == x.m_header_ &&
           m_lidardatadet_ == x.m_lidardatadet_ &&
           m_suffix_ == x.m_suffix_);
    }

    /*!
     * @brief Comparison operator.
     * @param x LidarDataDetection object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const LidarDataDetection& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member header_
     * @param _header_ New value to be copied in member header_
     */
    eProsima_user_DllExport void header_(
            const Header& _header_)
    {
        m_header_ = _header_;
    }

    /*!
     * @brief This function moves the value in member header_
     * @param _header_ New value to be moved in member header_
     */
    eProsima_user_DllExport void header_(
            Header&& _header_)
    {
        m_header_ = std::move(_header_);
    }

    /*!
     * @brief This function returns a constant reference to member header_
     * @return Constant reference to member header_
     */
    eProsima_user_DllExport const Header& header_() const
    {
        return m_header_;
    }

    /*!
     * @brief This function returns a reference to member header_
     * @return Reference to member header_
     */
    eProsima_user_DllExport Header& header_()
    {
        return m_header_;
    }


    /*!
     * @brief This function copies the value in member lidardatadet_
     * @param _lidardatadet_ New value to be copied in member lidardatadet_
     */
    eProsima_user_DllExport void lidardatadet_(
            const LidarDataDet& _lidardatadet_)
    {
        m_lidardatadet_ = _lidardatadet_;
    }

    /*!
     * @brief This function moves the value in member lidardatadet_
     * @param _lidardatadet_ New value to be moved in member lidardatadet_
     */
    eProsima_user_DllExport void lidardatadet_(
            LidarDataDet&& _lidardatadet_)
    {
        m_lidardatadet_ = std::move(_lidardatadet_);
    }

    /*!
     * @brief This function returns a constant reference to member lidardatadet_
     * @return Constant reference to member lidardatadet_
     */
    eProsima_user_DllExport const LidarDataDet& lidardatadet_() const
    {
        return m_lidardatadet_;
    }

    /*!
     * @brief This function returns a reference to member lidardatadet_
     * @return Reference to member lidardatadet_
     */
    eProsima_user_DllExport LidarDataDet& lidardatadet_()
    {
        return m_lidardatadet_;
    }


    /*!
     * @brief This function copies the value in member suffix_
     * @param _suffix_ New value to be copied in member suffix_
     */
    eProsima_user_DllExport void suffix_(
            const Suffix& _suffix_)
    {
        m_suffix_ = _suffix_;
    }

    /*!
     * @brief This function moves the value in member suffix_
     * @param _suffix_ New value to be moved in member suffix_
     */
    eProsima_user_DllExport void suffix_(
            Suffix&& _suffix_)
    {
        m_suffix_ = std::move(_suffix_);
    }

    /*!
     * @brief This function returns a constant reference to member suffix_
     * @return Constant reference to member suffix_
     */
    eProsima_user_DllExport const Suffix& suffix_() const
    {
        return m_suffix_;
    }

    /*!
     * @brief This function returns a reference to member suffix_
     * @return Reference to member suffix_
     */
    eProsima_user_DllExport Suffix& suffix_()
    {
        return m_suffix_;
    }



private:

    Header m_header_;
    LidarDataDet m_lidardatadet_;
    Suffix m_suffix_;

};

} // namespace Lidar

#endif // _FAST_DDS_GENERATED_LIDAR_LIDARDATA_HPP_


