// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file lidardataTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen.
 */

#include "lidardataTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "lidardata.hpp"


using namespace eprosima::fastdds::dds::xtypes;

namespace Lidar {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_Header_type_identifier(
        TypeIdentifierPair& type_ids_Header)
{

    ReturnCode_t return_code_Header {eprosima::fastdds::dds::RETCODE_OK};
    return_code_Header =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "Lidar::Header", type_ids_Header);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_Header)
    {
        StructTypeFlag struct_flags_Header = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL,
                false, false);
        QualifiedTypeName type_name_Header = "Lidar::Header";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_Header;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_Header;
        AppliedAnnotationSeq tmp_ann_custom_Header;
        eprosima::fastcdr::optional<AppliedVerbatimAnnotation> verbatim_Header;
        if (!tmp_ann_custom_Header.empty())
        {
            ann_custom_Header = tmp_ann_custom_Header;
        }

        CompleteTypeDetail detail_Header = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_Header, ann_custom_Header, type_name_Header.to_string());
        CompleteStructHeader header_Header;
        header_Header = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_Header);
        CompleteStructMemberSeq member_seq_Header;
        {
            TypeIdentifierPair type_ids_seq;
            ReturnCode_t return_code_seq {eprosima::fastdds::dds::RETCODE_OK};
            return_code_seq =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint32_t", type_ids_seq);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_seq)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "seq Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_seq = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_seq = 0x00000000;
            bool common_seq_ec {false};
            CommonStructMember common_seq {TypeObjectUtils::build_common_struct_member(member_id_seq, member_flags_seq, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_seq, common_seq_ec))};
            if (!common_seq_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure seq member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_seq = "seq";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_seq;
            ann_custom_Header.reset();
            CompleteMemberDetail detail_seq = TypeObjectUtils::build_complete_member_detail(name_seq, member_ann_builtin_seq, ann_custom_Header);
            CompleteStructMember member_seq = TypeObjectUtils::build_complete_struct_member(common_seq, detail_seq);
            TypeObjectUtils::add_complete_struct_member(member_seq_Header, member_seq);
        }
        {
            TypeIdentifierPair type_ids_timestamp_sec;
            ReturnCode_t return_code_timestamp_sec {eprosima::fastdds::dds::RETCODE_OK};
            return_code_timestamp_sec =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint32_t", type_ids_timestamp_sec);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_timestamp_sec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "timestamp_sec Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_timestamp_sec = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_timestamp_sec = 0x00000001;
            bool common_timestamp_sec_ec {false};
            CommonStructMember common_timestamp_sec {TypeObjectUtils::build_common_struct_member(member_id_timestamp_sec, member_flags_timestamp_sec, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_timestamp_sec, common_timestamp_sec_ec))};
            if (!common_timestamp_sec_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure timestamp_sec member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_timestamp_sec = "timestamp_sec";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_timestamp_sec;
            ann_custom_Header.reset();
            CompleteMemberDetail detail_timestamp_sec = TypeObjectUtils::build_complete_member_detail(name_timestamp_sec, member_ann_builtin_timestamp_sec, ann_custom_Header);
            CompleteStructMember member_timestamp_sec = TypeObjectUtils::build_complete_struct_member(common_timestamp_sec, detail_timestamp_sec);
            TypeObjectUtils::add_complete_struct_member(member_seq_Header, member_timestamp_sec);
        }
        {
            TypeIdentifierPair type_ids_timestamp_usec;
            ReturnCode_t return_code_timestamp_usec {eprosima::fastdds::dds::RETCODE_OK};
            return_code_timestamp_usec =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint32_t", type_ids_timestamp_usec);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_timestamp_usec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "timestamp_usec Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_timestamp_usec = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_timestamp_usec = 0x00000002;
            bool common_timestamp_usec_ec {false};
            CommonStructMember common_timestamp_usec {TypeObjectUtils::build_common_struct_member(member_id_timestamp_usec, member_flags_timestamp_usec, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_timestamp_usec, common_timestamp_usec_ec))};
            if (!common_timestamp_usec_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure timestamp_usec member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_timestamp_usec = "timestamp_usec";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_timestamp_usec;
            ann_custom_Header.reset();
            CompleteMemberDetail detail_timestamp_usec = TypeObjectUtils::build_complete_member_detail(name_timestamp_usec, member_ann_builtin_timestamp_usec, ann_custom_Header);
            CompleteStructMember member_timestamp_usec = TypeObjectUtils::build_complete_struct_member(common_timestamp_usec, detail_timestamp_usec);
            TypeObjectUtils::add_complete_struct_member(member_seq_Header, member_timestamp_usec);
        }
        {
            TypeIdentifierPair type_ids_utc_timestamp_sec;
            ReturnCode_t return_code_utc_timestamp_sec {eprosima::fastdds::dds::RETCODE_OK};
            return_code_utc_timestamp_sec =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint64_t", type_ids_utc_timestamp_sec);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_utc_timestamp_sec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "utc_timestamp_sec Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_utc_timestamp_sec = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_utc_timestamp_sec = 0x00000003;
            bool common_utc_timestamp_sec_ec {false};
            CommonStructMember common_utc_timestamp_sec {TypeObjectUtils::build_common_struct_member(member_id_utc_timestamp_sec, member_flags_utc_timestamp_sec, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_utc_timestamp_sec, common_utc_timestamp_sec_ec))};
            if (!common_utc_timestamp_sec_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure utc_timestamp_sec member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_utc_timestamp_sec = "utc_timestamp_sec";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_utc_timestamp_sec;
            ann_custom_Header.reset();
            CompleteMemberDetail detail_utc_timestamp_sec = TypeObjectUtils::build_complete_member_detail(name_utc_timestamp_sec, member_ann_builtin_utc_timestamp_sec, ann_custom_Header);
            CompleteStructMember member_utc_timestamp_sec = TypeObjectUtils::build_complete_struct_member(common_utc_timestamp_sec, detail_utc_timestamp_sec);
            TypeObjectUtils::add_complete_struct_member(member_seq_Header, member_utc_timestamp_sec);
        }
        {
            TypeIdentifierPair type_ids_topic;
            ReturnCode_t return_code_topic {eprosima::fastdds::dds::RETCODE_OK};
            return_code_topic =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_uint8_t_64", type_ids_topic);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_topic)
            {
                return_code_topic =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_byte", type_ids_topic);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_topic)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_uint8_t_64_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_uint8_t_64 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_topic, element_identifier_anonymous_array_uint8_t_64_ec))};
                if (!element_identifier_anonymous_array_uint8_t_64_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_uint8_t_64 = EK_COMPLETE;
                if (TK_NONE == type_ids_topic.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_uint8_t_64 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_uint8_t_64 = 0;
                PlainCollectionHeader header_anonymous_array_uint8_t_64 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_uint8_t_64, element_flags_anonymous_array_uint8_t_64);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(64));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_uint8_t_64, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_uint8_t_64));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_uint8_t_64", type_ids_topic))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_uint8_t_64 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_topic = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_topic = 0x00000004;
            bool common_topic_ec {false};
            CommonStructMember common_topic {TypeObjectUtils::build_common_struct_member(member_id_topic, member_flags_topic, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_topic, common_topic_ec))};
            if (!common_topic_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure topic member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_topic = "topic";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_topic;
            ann_custom_Header.reset();
            CompleteMemberDetail detail_topic = TypeObjectUtils::build_complete_member_detail(name_topic, member_ann_builtin_topic, ann_custom_Header);
            CompleteStructMember member_topic = TypeObjectUtils::build_complete_struct_member(common_topic, detail_topic);
            TypeObjectUtils::add_complete_struct_member(member_seq_Header, member_topic);
        }
        {
            TypeIdentifierPair type_ids_cycle_time;
            ReturnCode_t return_code_cycle_time {eprosima::fastdds::dds::RETCODE_OK};
            return_code_cycle_time =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint32_t", type_ids_cycle_time);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_cycle_time)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "cycle_time Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_cycle_time = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_cycle_time = 0x00000005;
            bool common_cycle_time_ec {false};
            CommonStructMember common_cycle_time {TypeObjectUtils::build_common_struct_member(member_id_cycle_time, member_flags_cycle_time, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_cycle_time, common_cycle_time_ec))};
            if (!common_cycle_time_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure cycle_time member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_cycle_time = "cycle_time";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_cycle_time;
            ann_custom_Header.reset();
            CompleteMemberDetail detail_cycle_time = TypeObjectUtils::build_complete_member_detail(name_cycle_time, member_ann_builtin_cycle_time, ann_custom_Header);
            CompleteStructMember member_cycle_time = TypeObjectUtils::build_complete_struct_member(common_cycle_time, detail_cycle_time);
            TypeObjectUtils::add_complete_struct_member(member_seq_Header, member_cycle_time);
        }
        CompleteStructType struct_type_Header = TypeObjectUtils::build_complete_struct_type(struct_flags_Header, header_Header, member_seq_Header);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_Header, type_name_Header.to_string(), type_ids_Header))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "Lidar::Header already registered in TypeObjectRegistry for a different type.");
        }
    }
}
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_Suffix_type_identifier(
        TypeIdentifierPair& type_ids_Suffix)
{

    ReturnCode_t return_code_Suffix {eprosima::fastdds::dds::RETCODE_OK};
    return_code_Suffix =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "Lidar::Suffix", type_ids_Suffix);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_Suffix)
    {
        StructTypeFlag struct_flags_Suffix = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL,
                false, false);
        QualifiedTypeName type_name_Suffix = "Lidar::Suffix";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_Suffix;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_Suffix;
        AppliedAnnotationSeq tmp_ann_custom_Suffix;
        eprosima::fastcdr::optional<AppliedVerbatimAnnotation> verbatim_Suffix;
        if (!tmp_ann_custom_Suffix.empty())
        {
            ann_custom_Suffix = tmp_ann_custom_Suffix;
        }

        CompleteTypeDetail detail_Suffix = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_Suffix, ann_custom_Suffix, type_name_Suffix.to_string());
        CompleteStructHeader header_Suffix;
        header_Suffix = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_Suffix);
        CompleteStructMemberSeq member_seq_Suffix;
        {
            TypeIdentifierPair type_ids_suff;
            ReturnCode_t return_code_suff {eprosima::fastdds::dds::RETCODE_OK};
            return_code_suff =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_uint8_t_64", type_ids_suff);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_suff)
            {
                return_code_suff =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_byte", type_ids_suff);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_suff)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_uint8_t_64_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_uint8_t_64 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_suff, element_identifier_anonymous_array_uint8_t_64_ec))};
                if (!element_identifier_anonymous_array_uint8_t_64_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_uint8_t_64 = EK_COMPLETE;
                if (TK_NONE == type_ids_suff.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_uint8_t_64 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_uint8_t_64 = 0;
                PlainCollectionHeader header_anonymous_array_uint8_t_64 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_uint8_t_64, element_flags_anonymous_array_uint8_t_64);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(64));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_uint8_t_64, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_uint8_t_64));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_uint8_t_64", type_ids_suff))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_uint8_t_64 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_suff = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_suff = 0x00000000;
            bool common_suff_ec {false};
            CommonStructMember common_suff {TypeObjectUtils::build_common_struct_member(member_id_suff, member_flags_suff, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_suff, common_suff_ec))};
            if (!common_suff_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure suff member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_suff = "suff";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_suff;
            ann_custom_Suffix.reset();
            CompleteMemberDetail detail_suff = TypeObjectUtils::build_complete_member_detail(name_suff, member_ann_builtin_suff, ann_custom_Suffix);
            CompleteStructMember member_suff = TypeObjectUtils::build_complete_struct_member(common_suff, detail_suff);
            TypeObjectUtils::add_complete_struct_member(member_seq_Suffix, member_suff);
        }
        CompleteStructType struct_type_Suffix = TypeObjectUtils::build_complete_struct_type(struct_flags_Suffix, header_Suffix, member_seq_Suffix);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_Suffix, type_name_Suffix.to_string(), type_ids_Suffix))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "Lidar::Suffix already registered in TypeObjectRegistry for a different type.");
        }
    }
}
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_ChannelData_type_identifier(
        TypeIdentifierPair& type_ids_ChannelData)
{

    ReturnCode_t return_code_ChannelData {eprosima::fastdds::dds::RETCODE_OK};
    return_code_ChannelData =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "Lidar::ChannelData", type_ids_ChannelData);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_ChannelData)
    {
        StructTypeFlag struct_flags_ChannelData = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL,
                false, false);
        QualifiedTypeName type_name_ChannelData = "Lidar::ChannelData";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_ChannelData;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_ChannelData;
        AppliedAnnotationSeq tmp_ann_custom_ChannelData;
        eprosima::fastcdr::optional<AppliedVerbatimAnnotation> verbatim_ChannelData;
        if (!tmp_ann_custom_ChannelData.empty())
        {
            ann_custom_ChannelData = tmp_ann_custom_ChannelData;
        }

        CompleteTypeDetail detail_ChannelData = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_ChannelData, ann_custom_ChannelData, type_name_ChannelData.to_string());
        CompleteStructHeader header_ChannelData;
        header_ChannelData = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_ChannelData);
        CompleteStructMemberSeq member_seq_ChannelData;
        {
            TypeIdentifierPair type_ids_x;
            ReturnCode_t return_code_x {eprosima::fastdds::dds::RETCODE_OK};
            return_code_x =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_x);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_x)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "x Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_x = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_x = 0x00000000;
            bool common_x_ec {false};
            CommonStructMember common_x {TypeObjectUtils::build_common_struct_member(member_id_x, member_flags_x, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_x, common_x_ec))};
            if (!common_x_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure x member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_x = "x";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_x;
            ann_custom_ChannelData.reset();
            CompleteMemberDetail detail_x = TypeObjectUtils::build_complete_member_detail(name_x, member_ann_builtin_x, ann_custom_ChannelData);
            CompleteStructMember member_x = TypeObjectUtils::build_complete_struct_member(common_x, detail_x);
            TypeObjectUtils::add_complete_struct_member(member_seq_ChannelData, member_x);
        }
        {
            TypeIdentifierPair type_ids_y;
            ReturnCode_t return_code_y {eprosima::fastdds::dds::RETCODE_OK};
            return_code_y =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_y);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_y)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "y Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_y = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_y = 0x00000001;
            bool common_y_ec {false};
            CommonStructMember common_y {TypeObjectUtils::build_common_struct_member(member_id_y, member_flags_y, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_y, common_y_ec))};
            if (!common_y_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure y member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_y = "y";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_y;
            ann_custom_ChannelData.reset();
            CompleteMemberDetail detail_y = TypeObjectUtils::build_complete_member_detail(name_y, member_ann_builtin_y, ann_custom_ChannelData);
            CompleteStructMember member_y = TypeObjectUtils::build_complete_struct_member(common_y, detail_y);
            TypeObjectUtils::add_complete_struct_member(member_seq_ChannelData, member_y);
        }
        {
            TypeIdentifierPair type_ids_z;
            ReturnCode_t return_code_z {eprosima::fastdds::dds::RETCODE_OK};
            return_code_z =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_z);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_z)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "z Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_z = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_z = 0x00000002;
            bool common_z_ec {false};
            CommonStructMember common_z {TypeObjectUtils::build_common_struct_member(member_id_z, member_flags_z, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_z, common_z_ec))};
            if (!common_z_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure z member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_z = "z";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_z;
            ann_custom_ChannelData.reset();
            CompleteMemberDetail detail_z = TypeObjectUtils::build_complete_member_detail(name_z, member_ann_builtin_z, ann_custom_ChannelData);
            CompleteStructMember member_z = TypeObjectUtils::build_complete_struct_member(common_z, detail_z);
            TypeObjectUtils::add_complete_struct_member(member_seq_ChannelData, member_z);
        }
        {
            TypeIdentifierPair type_ids_intensity;
            ReturnCode_t return_code_intensity {eprosima::fastdds::dds::RETCODE_OK};
            return_code_intensity =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_byte", type_ids_intensity);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_intensity)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "intensity Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_intensity = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_intensity = 0x00000003;
            bool common_intensity_ec {false};
            CommonStructMember common_intensity {TypeObjectUtils::build_common_struct_member(member_id_intensity, member_flags_intensity, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_intensity, common_intensity_ec))};
            if (!common_intensity_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure intensity member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_intensity = "intensity";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_intensity;
            ann_custom_ChannelData.reset();
            CompleteMemberDetail detail_intensity = TypeObjectUtils::build_complete_member_detail(name_intensity, member_ann_builtin_intensity, ann_custom_ChannelData);
            CompleteStructMember member_intensity = TypeObjectUtils::build_complete_struct_member(common_intensity, detail_intensity);
            TypeObjectUtils::add_complete_struct_member(member_seq_ChannelData, member_intensity);
        }
        CompleteStructType struct_type_ChannelData = TypeObjectUtils::build_complete_struct_type(struct_flags_ChannelData, header_ChannelData, member_seq_ChannelData);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_ChannelData, type_name_ChannelData.to_string(), type_ids_ChannelData))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "Lidar::ChannelData already registered in TypeObjectRegistry for a different type.");
        }
    }
}
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_DataBlock_type_identifier(
        TypeIdentifierPair& type_ids_DataBlock)
{

    ReturnCode_t return_code_DataBlock {eprosima::fastdds::dds::RETCODE_OK};
    return_code_DataBlock =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "Lidar::DataBlock", type_ids_DataBlock);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_DataBlock)
    {
        StructTypeFlag struct_flags_DataBlock = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_DataBlock = "Lidar::DataBlock";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_DataBlock;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_DataBlock;
        CompleteTypeDetail detail_DataBlock = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_DataBlock, ann_custom_DataBlock, type_name_DataBlock.to_string());
        CompleteStructHeader header_DataBlock;
        header_DataBlock = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_DataBlock);
        CompleteStructMemberSeq member_seq_DataBlock;
        {
            TypeIdentifierPair type_ids_time_offset;
            ReturnCode_t return_code_time_offset {eprosima::fastdds::dds::RETCODE_OK};
            return_code_time_offset =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_byte", type_ids_time_offset);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_time_offset)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "time_offset Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_time_offset = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_time_offset = 0x00000000;
            bool common_time_offset_ec {false};
            CommonStructMember common_time_offset {TypeObjectUtils::build_common_struct_member(member_id_time_offset, member_flags_time_offset, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_time_offset, common_time_offset_ec))};
            if (!common_time_offset_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure time_offset member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_time_offset = "time_offset";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_time_offset;
            ann_custom_DataBlock.reset();
            CompleteMemberDetail detail_time_offset = TypeObjectUtils::build_complete_member_detail(name_time_offset, member_ann_builtin_time_offset, ann_custom_DataBlock);
            CompleteStructMember member_time_offset = TypeObjectUtils::build_complete_struct_member(common_time_offset, detail_time_offset);
            TypeObjectUtils::add_complete_struct_member(member_seq_DataBlock, member_time_offset);
        }
        {
            TypeIdentifierPair type_ids_return_seq;
            ReturnCode_t return_code_return_seq {eprosima::fastdds::dds::RETCODE_OK};
            return_code_return_seq =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_byte", type_ids_return_seq);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_return_seq)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "return_seq Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_return_seq = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_return_seq = 0x00000001;
            bool common_return_seq_ec {false};
            CommonStructMember common_return_seq {TypeObjectUtils::build_common_struct_member(member_id_return_seq, member_flags_return_seq, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_return_seq, common_return_seq_ec))};
            if (!common_return_seq_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure return_seq member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_return_seq = "return_seq";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_return_seq;
            ann_custom_DataBlock.reset();
            CompleteMemberDetail detail_return_seq = TypeObjectUtils::build_complete_member_detail(name_return_seq, member_ann_builtin_return_seq, ann_custom_DataBlock);
            CompleteStructMember member_return_seq = TypeObjectUtils::build_complete_struct_member(common_return_seq, detail_return_seq);
            TypeObjectUtils::add_complete_struct_member(member_seq_DataBlock, member_return_seq);
        }
        {
            TypeIdentifierPair type_ids_channel_data_sum;
            ReturnCode_t return_code_channel_data_sum {eprosima::fastdds::dds::RETCODE_OK};
            return_code_channel_data_sum =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint16_t", type_ids_channel_data_sum);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_channel_data_sum)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "channel_data_sum Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_channel_data_sum = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_channel_data_sum = 0x00000002;
            bool common_channel_data_sum_ec {false};
            CommonStructMember common_channel_data_sum {TypeObjectUtils::build_common_struct_member(member_id_channel_data_sum, member_flags_channel_data_sum, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_channel_data_sum, common_channel_data_sum_ec))};
            if (!common_channel_data_sum_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure channel_data_sum member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_channel_data_sum = "channel_data_sum";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_channel_data_sum;
            ann_custom_DataBlock.reset();
            CompleteMemberDetail detail_channel_data_sum = TypeObjectUtils::build_complete_member_detail(name_channel_data_sum, member_ann_builtin_channel_data_sum, ann_custom_DataBlock);
            CompleteStructMember member_channel_data_sum = TypeObjectUtils::build_complete_struct_member(common_channel_data_sum, detail_channel_data_sum);
            TypeObjectUtils::add_complete_struct_member(member_seq_DataBlock, member_channel_data_sum);
        }
        {
            TypeIdentifierPair type_ids_channel_data_list;
            ReturnCode_t return_code_channel_data_list {eprosima::fastdds::dds::RETCODE_OK};
            return_code_channel_data_list =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_Lidar_ChannelData_5", type_ids_channel_data_list);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_channel_data_list)
            {
                return_code_channel_data_list =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "Lidar::ChannelData", type_ids_channel_data_list);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_channel_data_list)
                {
                    Lidar::register_ChannelData_type_identifier(type_ids_channel_data_list);
                }
                bool element_identifier_anonymous_array_Lidar_ChannelData_5_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_Lidar_ChannelData_5 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_channel_data_list, element_identifier_anonymous_array_Lidar_ChannelData_5_ec))};
                if (!element_identifier_anonymous_array_Lidar_ChannelData_5_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_Lidar_ChannelData_5 = EK_COMPLETE;
                if (TK_NONE == type_ids_channel_data_list.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_Lidar_ChannelData_5 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_Lidar_ChannelData_5 = 0;
                PlainCollectionHeader header_anonymous_array_Lidar_ChannelData_5 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_Lidar_ChannelData_5, element_flags_anonymous_array_Lidar_ChannelData_5);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(5));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_Lidar_ChannelData_5, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_Lidar_ChannelData_5));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_Lidar_ChannelData_5", type_ids_channel_data_list))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_Lidar_ChannelData_5 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_channel_data_list = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_channel_data_list = 0x00000003;
            bool common_channel_data_list_ec {false};
            CommonStructMember common_channel_data_list {TypeObjectUtils::build_common_struct_member(member_id_channel_data_list, member_flags_channel_data_list, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_channel_data_list, common_channel_data_list_ec))};
            if (!common_channel_data_list_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure channel_data_list member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_channel_data_list = "channel_data_list";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_channel_data_list;
            ann_custom_DataBlock.reset();
            CompleteMemberDetail detail_channel_data_list = TypeObjectUtils::build_complete_member_detail(name_channel_data_list, member_ann_builtin_channel_data_list, ann_custom_DataBlock);
            CompleteStructMember member_channel_data_list = TypeObjectUtils::build_complete_struct_member(common_channel_data_list, detail_channel_data_list);
            TypeObjectUtils::add_complete_struct_member(member_seq_DataBlock, member_channel_data_list);
        }
        CompleteStructType struct_type_DataBlock = TypeObjectUtils::build_complete_struct_type(struct_flags_DataBlock, header_DataBlock, member_seq_DataBlock);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_DataBlock, type_name_DataBlock.to_string(), type_ids_DataBlock))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "Lidar::DataBlock already registered in TypeObjectRegistry for a different type.");
        }
    }
}
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_Packet_type_identifier(
        TypeIdentifierPair& type_ids_Packet)
{

    ReturnCode_t return_code_Packet {eprosima::fastdds::dds::RETCODE_OK};
    return_code_Packet =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "Lidar::Packet", type_ids_Packet);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_Packet)
    {
        StructTypeFlag struct_flags_Packet = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_Packet = "Lidar::Packet";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_Packet;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_Packet;
        CompleteTypeDetail detail_Packet = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_Packet, ann_custom_Packet, type_name_Packet.to_string());
        CompleteStructHeader header_Packet;
        header_Packet = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_Packet);
        CompleteStructMemberSeq member_seq_Packet;
        {
            TypeIdentifierPair type_ids_timestamp_secs;
            ReturnCode_t return_code_timestamp_secs {eprosima::fastdds::dds::RETCODE_OK};
            return_code_timestamp_secs =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint32_t", type_ids_timestamp_secs);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_timestamp_secs)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "timestamp_secs Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_timestamp_secs = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_timestamp_secs = 0x00000000;
            bool common_timestamp_secs_ec {false};
            CommonStructMember common_timestamp_secs {TypeObjectUtils::build_common_struct_member(member_id_timestamp_secs, member_flags_timestamp_secs, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_timestamp_secs, common_timestamp_secs_ec))};
            if (!common_timestamp_secs_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure timestamp_secs member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_timestamp_secs = "timestamp_secs";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_timestamp_secs;
            ann_custom_Packet.reset();
            CompleteMemberDetail detail_timestamp_secs = TypeObjectUtils::build_complete_member_detail(name_timestamp_secs, member_ann_builtin_timestamp_secs, ann_custom_Packet);
            CompleteStructMember member_timestamp_secs = TypeObjectUtils::build_complete_struct_member(common_timestamp_secs, detail_timestamp_secs);
            TypeObjectUtils::add_complete_struct_member(member_seq_Packet, member_timestamp_secs);
        }
        {
            TypeIdentifierPair type_ids_timestamp_usecs;
            ReturnCode_t return_code_timestamp_usecs {eprosima::fastdds::dds::RETCODE_OK};
            return_code_timestamp_usecs =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint32_t", type_ids_timestamp_usecs);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_timestamp_usecs)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "timestamp_usecs Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_timestamp_usecs = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_timestamp_usecs = 0x00000001;
            bool common_timestamp_usecs_ec {false};
            CommonStructMember common_timestamp_usecs {TypeObjectUtils::build_common_struct_member(member_id_timestamp_usecs, member_flags_timestamp_usecs, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_timestamp_usecs, common_timestamp_usecs_ec))};
            if (!common_timestamp_usecs_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure timestamp_usecs member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_timestamp_usecs = "timestamp_usecs";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_timestamp_usecs;
            ann_custom_Packet.reset();
            CompleteMemberDetail detail_timestamp_usecs = TypeObjectUtils::build_complete_member_detail(name_timestamp_usecs, member_ann_builtin_timestamp_usecs, ann_custom_Packet);
            CompleteStructMember member_timestamp_usecs = TypeObjectUtils::build_complete_struct_member(common_timestamp_usecs, detail_timestamp_usecs);
            TypeObjectUtils::add_complete_struct_member(member_seq_Packet, member_timestamp_usecs);
        }
        {
            TypeIdentifierPair type_ids_laser_num;
            ReturnCode_t return_code_laser_num {eprosima::fastdds::dds::RETCODE_OK};
            return_code_laser_num =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_byte", type_ids_laser_num);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_laser_num)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "laser_num Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_laser_num = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_laser_num = 0x00000002;
            bool common_laser_num_ec {false};
            CommonStructMember common_laser_num {TypeObjectUtils::build_common_struct_member(member_id_laser_num, member_flags_laser_num, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_laser_num, common_laser_num_ec))};
            if (!common_laser_num_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure laser_num member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_laser_num = "laser_num";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_laser_num;
            ann_custom_Packet.reset();
            CompleteMemberDetail detail_laser_num = TypeObjectUtils::build_complete_member_detail(name_laser_num, member_ann_builtin_laser_num, ann_custom_Packet);
            CompleteStructMember member_laser_num = TypeObjectUtils::build_complete_struct_member(common_laser_num, detail_laser_num);
            TypeObjectUtils::add_complete_struct_member(member_seq_Packet, member_laser_num);
        }
        {
            TypeIdentifierPair type_ids_data_block_sum;
            ReturnCode_t return_code_data_block_sum {eprosima::fastdds::dds::RETCODE_OK};
            return_code_data_block_sum =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint16_t", type_ids_data_block_sum);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_data_block_sum)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "data_block_sum Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_data_block_sum = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_data_block_sum = 0x00000003;
            bool common_data_block_sum_ec {false};
            CommonStructMember common_data_block_sum {TypeObjectUtils::build_common_struct_member(member_id_data_block_sum, member_flags_data_block_sum, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_data_block_sum, common_data_block_sum_ec))};
            if (!common_data_block_sum_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure data_block_sum member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_data_block_sum = "data_block_sum";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_data_block_sum;
            ann_custom_Packet.reset();
            CompleteMemberDetail detail_data_block_sum = TypeObjectUtils::build_complete_member_detail(name_data_block_sum, member_ann_builtin_data_block_sum, ann_custom_Packet);
            CompleteStructMember member_data_block_sum = TypeObjectUtils::build_complete_struct_member(common_data_block_sum, detail_data_block_sum);
            TypeObjectUtils::add_complete_struct_member(member_seq_Packet, member_data_block_sum);
        }
        {
            TypeIdentifierPair type_ids_data_block_list;
            ReturnCode_t return_code_data_block_list {eprosima::fastdds::dds::RETCODE_OK};
            return_code_data_block_list =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_Lidar_DataBlock_25", type_ids_data_block_list);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_data_block_list)
            {
                return_code_data_block_list =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "Lidar::DataBlock", type_ids_data_block_list);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_data_block_list)
                {
                    Lidar::register_DataBlock_type_identifier(type_ids_data_block_list);
                }
                bool element_identifier_anonymous_array_Lidar_DataBlock_25_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_Lidar_DataBlock_25 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_data_block_list, element_identifier_anonymous_array_Lidar_DataBlock_25_ec))};
                if (!element_identifier_anonymous_array_Lidar_DataBlock_25_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_Lidar_DataBlock_25 = EK_COMPLETE;
                if (TK_NONE == type_ids_data_block_list.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_Lidar_DataBlock_25 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_Lidar_DataBlock_25 = 0;
                PlainCollectionHeader header_anonymous_array_Lidar_DataBlock_25 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_Lidar_DataBlock_25, element_flags_anonymous_array_Lidar_DataBlock_25);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(25));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_Lidar_DataBlock_25, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_Lidar_DataBlock_25));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_Lidar_DataBlock_25", type_ids_data_block_list))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_Lidar_DataBlock_25 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_data_block_list = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_data_block_list = 0x00000004;
            bool common_data_block_list_ec {false};
            CommonStructMember common_data_block_list {TypeObjectUtils::build_common_struct_member(member_id_data_block_list, member_flags_data_block_list, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_data_block_list, common_data_block_list_ec))};
            if (!common_data_block_list_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure data_block_list member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_data_block_list = "data_block_list";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_data_block_list;
            ann_custom_Packet.reset();
            CompleteMemberDetail detail_data_block_list = TypeObjectUtils::build_complete_member_detail(name_data_block_list, member_ann_builtin_data_block_list, ann_custom_Packet);
            CompleteStructMember member_data_block_list = TypeObjectUtils::build_complete_struct_member(common_data_block_list, detail_data_block_list);
            TypeObjectUtils::add_complete_struct_member(member_seq_Packet, member_data_block_list);
        }
        CompleteStructType struct_type_Packet = TypeObjectUtils::build_complete_struct_type(struct_flags_Packet, header_Packet, member_seq_Packet);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_Packet, type_name_Packet.to_string(), type_ids_Packet))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "Lidar::Packet already registered in TypeObjectRegistry for a different type.");
        }
    }
}
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_LidarDataDet_type_identifier(
        TypeIdentifierPair& type_ids_LidarDataDet)
{

    ReturnCode_t return_code_LidarDataDet {eprosima::fastdds::dds::RETCODE_OK};
    return_code_LidarDataDet =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "Lidar::LidarDataDet", type_ids_LidarDataDet);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_LidarDataDet)
    {
        StructTypeFlag struct_flags_LidarDataDet = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_LidarDataDet = "Lidar::LidarDataDet";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_LidarDataDet;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_LidarDataDet;
        CompleteTypeDetail detail_LidarDataDet = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_LidarDataDet, ann_custom_LidarDataDet, type_name_LidarDataDet.to_string());
        CompleteStructHeader header_LidarDataDet;
        header_LidarDataDet = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_LidarDataDet);
        CompleteStructMemberSeq member_seq_LidarDataDet;
        {
            TypeIdentifierPair type_ids_protocol_version;
            ReturnCode_t return_code_protocol_version {eprosima::fastdds::dds::RETCODE_OK};
            return_code_protocol_version =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint16_t", type_ids_protocol_version);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_protocol_version)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "protocol_version Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_protocol_version = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_protocol_version = 0x00000000;
            bool common_protocol_version_ec {false};
            CommonStructMember common_protocol_version {TypeObjectUtils::build_common_struct_member(member_id_protocol_version, member_flags_protocol_version, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_protocol_version, common_protocol_version_ec))};
            if (!common_protocol_version_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure protocol_version member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_protocol_version = "protocol_version";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_protocol_version;
            ann_custom_LidarDataDet.reset();
            CompleteMemberDetail detail_protocol_version = TypeObjectUtils::build_complete_member_detail(name_protocol_version, member_ann_builtin_protocol_version, ann_custom_LidarDataDet);
            CompleteStructMember member_protocol_version = TypeObjectUtils::build_complete_struct_member(common_protocol_version, detail_protocol_version);
            TypeObjectUtils::add_complete_struct_member(member_seq_LidarDataDet, member_protocol_version);
        }
        {
            TypeIdentifierPair type_ids_return_mode;
            ReturnCode_t return_code_return_mode {eprosima::fastdds::dds::RETCODE_OK};
            return_code_return_mode =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_byte", type_ids_return_mode);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_return_mode)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "return_mode Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_return_mode = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_return_mode = 0x00000001;
            bool common_return_mode_ec {false};
            CommonStructMember common_return_mode {TypeObjectUtils::build_common_struct_member(member_id_return_mode, member_flags_return_mode, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_return_mode, common_return_mode_ec))};
            if (!common_return_mode_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure return_mode member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_return_mode = "return_mode";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_return_mode;
            ann_custom_LidarDataDet.reset();
            CompleteMemberDetail detail_return_mode = TypeObjectUtils::build_complete_member_detail(name_return_mode, member_ann_builtin_return_mode, ann_custom_LidarDataDet);
            CompleteStructMember member_return_mode = TypeObjectUtils::build_complete_struct_member(common_return_mode, detail_return_mode);
            TypeObjectUtils::add_complete_struct_member(member_seq_LidarDataDet, member_return_mode);
        }
        {
            TypeIdentifierPair type_ids_time_sync_mode;
            ReturnCode_t return_code_time_sync_mode {eprosima::fastdds::dds::RETCODE_OK};
            return_code_time_sync_mode =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_byte", type_ids_time_sync_mode);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_time_sync_mode)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "time_sync_mode Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_time_sync_mode = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_time_sync_mode = 0x00000002;
            bool common_time_sync_mode_ec {false};
            CommonStructMember common_time_sync_mode {TypeObjectUtils::build_common_struct_member(member_id_time_sync_mode, member_flags_time_sync_mode, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_time_sync_mode, common_time_sync_mode_ec))};
            if (!common_time_sync_mode_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure time_sync_mode member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_time_sync_mode = "time_sync_mode";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_time_sync_mode;
            ann_custom_LidarDataDet.reset();
            CompleteMemberDetail detail_time_sync_mode = TypeObjectUtils::build_complete_member_detail(name_time_sync_mode, member_ann_builtin_time_sync_mode, ann_custom_LidarDataDet);
            CompleteStructMember member_time_sync_mode = TypeObjectUtils::build_complete_struct_member(common_time_sync_mode, detail_time_sync_mode);
            TypeObjectUtils::add_complete_struct_member(member_seq_LidarDataDet, member_time_sync_mode);
        }
        {
            TypeIdentifierPair type_ids_frame_sync;
            ReturnCode_t return_code_frame_sync {eprosima::fastdds::dds::RETCODE_OK};
            return_code_frame_sync =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_byte", type_ids_frame_sync);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_frame_sync)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "frame_sync Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_frame_sync = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_frame_sync = 0x00000003;
            bool common_frame_sync_ec {false};
            CommonStructMember common_frame_sync {TypeObjectUtils::build_common_struct_member(member_id_frame_sync, member_flags_frame_sync, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_frame_sync, common_frame_sync_ec))};
            if (!common_frame_sync_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure frame_sync member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_frame_sync = "frame_sync";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_frame_sync;
            ann_custom_LidarDataDet.reset();
            CompleteMemberDetail detail_frame_sync = TypeObjectUtils::build_complete_member_detail(name_frame_sync, member_ann_builtin_frame_sync, ann_custom_LidarDataDet);
            CompleteStructMember member_frame_sync = TypeObjectUtils::build_complete_struct_member(common_frame_sync, detail_frame_sync);
            TypeObjectUtils::add_complete_struct_member(member_seq_LidarDataDet, member_frame_sync);
        }
        {
            TypeIdentifierPair type_ids_packet_sum;
            ReturnCode_t return_code_packet_sum {eprosima::fastdds::dds::RETCODE_OK};
            return_code_packet_sum =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint16_t", type_ids_packet_sum);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_packet_sum)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "packet_sum Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_packet_sum = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_packet_sum = 0x00000004;
            bool common_packet_sum_ec {false};
            CommonStructMember common_packet_sum {TypeObjectUtils::build_common_struct_member(member_id_packet_sum, member_flags_packet_sum, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_packet_sum, common_packet_sum_ec))};
            if (!common_packet_sum_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure packet_sum member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_packet_sum = "packet_sum";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_packet_sum;
            ann_custom_LidarDataDet.reset();
            CompleteMemberDetail detail_packet_sum = TypeObjectUtils::build_complete_member_detail(name_packet_sum, member_ann_builtin_packet_sum, ann_custom_LidarDataDet);
            CompleteStructMember member_packet_sum = TypeObjectUtils::build_complete_struct_member(common_packet_sum, detail_packet_sum);
            TypeObjectUtils::add_complete_struct_member(member_seq_LidarDataDet, member_packet_sum);
        }
        {
            TypeIdentifierPair type_ids_packet_list;
            ReturnCode_t return_code_packet_list {eprosima::fastdds::dds::RETCODE_OK};
            return_code_packet_list =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_Lidar_Packet_630", type_ids_packet_list);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_packet_list)
            {
                return_code_packet_list =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "Lidar::Packet", type_ids_packet_list);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_packet_list)
                {
                    Lidar::register_Packet_type_identifier(type_ids_packet_list);
                }
                bool element_identifier_anonymous_array_Lidar_Packet_630_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_Lidar_Packet_630 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_packet_list, element_identifier_anonymous_array_Lidar_Packet_630_ec))};
                if (!element_identifier_anonymous_array_Lidar_Packet_630_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_Lidar_Packet_630 = EK_COMPLETE;
                if (TK_NONE == type_ids_packet_list.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_Lidar_Packet_630 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_Lidar_Packet_630 = 0;
                PlainCollectionHeader header_anonymous_array_Lidar_Packet_630 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_Lidar_Packet_630, element_flags_anonymous_array_Lidar_Packet_630);
                {
                    LBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<LBound>(630));

                    PlainArrayLElemDefn array_ldefn = TypeObjectUtils::build_plain_array_l_elem_defn(header_anonymous_array_Lidar_Packet_630, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_Lidar_Packet_630));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_l_array_type_identifier(array_ldefn, "anonymous_array_Lidar_Packet_630", type_ids_packet_list))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_Lidar_Packet_630 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_packet_list = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_packet_list = 0x00000005;
            bool common_packet_list_ec {false};
            CommonStructMember common_packet_list {TypeObjectUtils::build_common_struct_member(member_id_packet_list, member_flags_packet_list, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_packet_list, common_packet_list_ec))};
            if (!common_packet_list_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure packet_list member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_packet_list = "packet_list";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_packet_list;
            ann_custom_LidarDataDet.reset();
            CompleteMemberDetail detail_packet_list = TypeObjectUtils::build_complete_member_detail(name_packet_list, member_ann_builtin_packet_list, ann_custom_LidarDataDet);
            CompleteStructMember member_packet_list = TypeObjectUtils::build_complete_struct_member(common_packet_list, detail_packet_list);
            TypeObjectUtils::add_complete_struct_member(member_seq_LidarDataDet, member_packet_list);
        }
        CompleteStructType struct_type_LidarDataDet = TypeObjectUtils::build_complete_struct_type(struct_flags_LidarDataDet, header_LidarDataDet, member_seq_LidarDataDet);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_LidarDataDet, type_name_LidarDataDet.to_string(), type_ids_LidarDataDet))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "Lidar::LidarDataDet already registered in TypeObjectRegistry for a different type.");
        }
    }
}
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_LidarDataDetection_type_identifier(
        TypeIdentifierPair& type_ids_LidarDataDetection)
{

    ReturnCode_t return_code_LidarDataDetection {eprosima::fastdds::dds::RETCODE_OK};
    return_code_LidarDataDetection =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "Lidar::LidarDataDetection", type_ids_LidarDataDetection);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_LidarDataDetection)
    {
        StructTypeFlag struct_flags_LidarDataDetection = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_LidarDataDetection = "Lidar::LidarDataDetection";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_LidarDataDetection;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_LidarDataDetection;
        CompleteTypeDetail detail_LidarDataDetection = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_LidarDataDetection, ann_custom_LidarDataDetection, type_name_LidarDataDetection.to_string());
        CompleteStructHeader header_LidarDataDetection;
        header_LidarDataDetection = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_LidarDataDetection);
        CompleteStructMemberSeq member_seq_LidarDataDetection;
        {
            TypeIdentifierPair type_ids_header_;
            ReturnCode_t return_code_header_ {eprosima::fastdds::dds::RETCODE_OK};
            return_code_header_ =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "Lidar::Header", type_ids_header_);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_header_)
            {
                Lidar::register_Header_type_identifier(type_ids_header_);
            }
            StructMemberFlag member_flags_header_ = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_header_ = 0x00000000;
            bool common_header__ec {false};
            CommonStructMember common_header_ {TypeObjectUtils::build_common_struct_member(member_id_header_, member_flags_header_, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_header_, common_header__ec))};
            if (!common_header__ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure header_ member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_header_ = "header_";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_header_;
            ann_custom_LidarDataDetection.reset();
            CompleteMemberDetail detail_header_ = TypeObjectUtils::build_complete_member_detail(name_header_, member_ann_builtin_header_, ann_custom_LidarDataDetection);
            CompleteStructMember member_header_ = TypeObjectUtils::build_complete_struct_member(common_header_, detail_header_);
            TypeObjectUtils::add_complete_struct_member(member_seq_LidarDataDetection, member_header_);
        }
        {
            TypeIdentifierPair type_ids_lidardatadet_;
            ReturnCode_t return_code_lidardatadet_ {eprosima::fastdds::dds::RETCODE_OK};
            return_code_lidardatadet_ =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "Lidar::LidarDataDet", type_ids_lidardatadet_);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_lidardatadet_)
            {
                Lidar::register_LidarDataDet_type_identifier(type_ids_lidardatadet_);
            }
            StructMemberFlag member_flags_lidardatadet_ = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_lidardatadet_ = 0x00000001;
            bool common_lidardatadet__ec {false};
            CommonStructMember common_lidardatadet_ {TypeObjectUtils::build_common_struct_member(member_id_lidardatadet_, member_flags_lidardatadet_, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_lidardatadet_, common_lidardatadet__ec))};
            if (!common_lidardatadet__ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure lidardatadet_ member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_lidardatadet_ = "lidardatadet_";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_lidardatadet_;
            ann_custom_LidarDataDetection.reset();
            CompleteMemberDetail detail_lidardatadet_ = TypeObjectUtils::build_complete_member_detail(name_lidardatadet_, member_ann_builtin_lidardatadet_, ann_custom_LidarDataDetection);
            CompleteStructMember member_lidardatadet_ = TypeObjectUtils::build_complete_struct_member(common_lidardatadet_, detail_lidardatadet_);
            TypeObjectUtils::add_complete_struct_member(member_seq_LidarDataDetection, member_lidardatadet_);
        }
        {
            TypeIdentifierPair type_ids_suffix_;
            ReturnCode_t return_code_suffix_ {eprosima::fastdds::dds::RETCODE_OK};
            return_code_suffix_ =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "Lidar::Suffix", type_ids_suffix_);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_suffix_)
            {
                Lidar::register_Suffix_type_identifier(type_ids_suffix_);
            }
            StructMemberFlag member_flags_suffix_ = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_suffix_ = 0x00000002;
            bool common_suffix__ec {false};
            CommonStructMember common_suffix_ {TypeObjectUtils::build_common_struct_member(member_id_suffix_, member_flags_suffix_, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_suffix_, common_suffix__ec))};
            if (!common_suffix__ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure suffix_ member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_suffix_ = "suffix_";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_suffix_;
            ann_custom_LidarDataDetection.reset();
            CompleteMemberDetail detail_suffix_ = TypeObjectUtils::build_complete_member_detail(name_suffix_, member_ann_builtin_suffix_, ann_custom_LidarDataDetection);
            CompleteStructMember member_suffix_ = TypeObjectUtils::build_complete_struct_member(common_suffix_, detail_suffix_);
            TypeObjectUtils::add_complete_struct_member(member_seq_LidarDataDetection, member_suffix_);
        }
        CompleteStructType struct_type_LidarDataDetection = TypeObjectUtils::build_complete_struct_type(struct_flags_LidarDataDetection, header_LidarDataDetection, member_seq_LidarDataDetection);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_LidarDataDetection, type_name_LidarDataDetection.to_string(), type_ids_LidarDataDetection))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "Lidar::LidarDataDetection already registered in TypeObjectRegistry for a different type.");
        }
    }
}

} // namespace Lidar

