// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file lidardataCdrAux.hpp
 * This source file contains some definitions of CDR related functions.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef FAST_DDS_GENERATED__LIDAR_LIDARDATACDRAUX_HPP
#define FAST_DDS_GENERATED__LIDAR_LIDARDATACDRAUX_HPP

#include "lidardata.hpp"

constexpr uint32_t Lidar_ChannelData_max_cdr_typesize {13UL};
constexpr uint32_t Lidar_ChannelData_max_key_cdr_typesize {0UL};

constexpr uint32_t Lidar_LidarDataDet_max_cdr_typesize {1461613UL};
constexpr uint32_t Lidar_LidarDataDet_max_key_cdr_typesize {0UL};

constexpr uint32_t Lidar_Header_max_cdr_typesize {92UL};
constexpr uint32_t Lidar_Header_max_key_cdr_typesize {0UL};

constexpr uint32_t Lidar_DataBlock_max_cdr_typesize {89UL};
constexpr uint32_t Lidar_DataBlock_max_key_cdr_typesize {0UL};

constexpr uint32_t Lidar_LidarDataDetection_max_cdr_typesize {1461769UL};
constexpr uint32_t Lidar_LidarDataDetection_max_key_cdr_typesize {0UL};

constexpr uint32_t Lidar_Packet_max_cdr_typesize {2317UL};
constexpr uint32_t Lidar_Packet_max_key_cdr_typesize {0UL};

constexpr uint32_t Lidar_Suffix_max_cdr_typesize {64UL};
constexpr uint32_t Lidar_Suffix_max_key_cdr_typesize {0UL};


namespace eprosima {
namespace fastcdr {

class Cdr;
class CdrSizeCalculator;

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const Lidar::Header& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const Lidar::Suffix& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const Lidar::ChannelData& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const Lidar::DataBlock& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const Lidar::Packet& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const Lidar::LidarDataDet& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const Lidar::LidarDataDetection& data);


} // namespace fastcdr
} // namespace eprosima

#endif // FAST_DDS_GENERATED__LIDAR_LIDARDATACDRAUX_HPP

